# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0002_auto_20160426_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='category',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='stars',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
