# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0003_auto_20160514_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='hotel_id',
        ),
        migrations.AddField(
            model_name='image',
            name='hotel_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hoteles.Hotel'),
            preserve_default=False,
        ),
    ]
