# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 11:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hoteles', '0004_auto_20160514_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddField(
            model_name='config',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='hotel_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='hotel_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hoteles.Hotel'),
        ),
        migrations.AlterField(
            model_name='image',
            name='hotel_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hoteles.Hotel'),
        ),
    ]
