# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 11:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0008_auto_20160515_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='hotel_id',
            new_name='hotel',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='hotel_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='hotel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hoteles.Hotel'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
