# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0009_auto_20160515_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='config',
            name='user',
            field=models.TextField(),
        ),
    ]
