# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0011_auto_20160515_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='size',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
