# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0012_auto_20160516_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
